# Generated by Django 4.2.6 on 2023-12-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht22',
            name='device_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dht22',
            name='ipaddr',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
