# Generated by Django 4.2.6 on 2023-12-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambient', '0002_dht22_device_name_dht22_ipaddr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht22',
            name='device_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dht22',
            name='ipaddr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
